# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1db9a2ceb8af1e20f5c705b96fed43766ac2d89e57a245e3585c38b3f28cd1e64c064233232a61e441da4f26ec890bcb0b58df3de57568306b6c62e1ec4cdab

test:
  secret_key_base: 6061f82f6e70e282ccd2baf3c92adfd69ea12be415bbb224e8add81de62c4cc3936c5b105547800d0c826bbbfd19129ade33e31e243ce939701a19f2397b49a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
